---
version: '3.2'

services:
  pw:
    build: .
    container_name: b
    environment:
      - TP_PWD=YourPassword
      - TP_URL=http://192.168.68.1/
      - TC_PWD=YourPassword
      - TC_URL=http://192.168.1.1/
      - TC_USR=YourUser
    network_mode: host
